name: Build Spy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Кодты алу
        uses: actions/checkout@v4

      - name: Python орнату
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Жүйелік кітапханаларды орнату
        run: |
          sudo apt update
          # libtinfo5-ті өткізіп жіберіп, қалғандарын орнатамыз
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer Cython==0.29.33

      - name: APK жинау (Buildozer)
        run: |
          # Buildozer-ді іске қосу
          yes | buildozer android debug
        continue-on-error: false

      - name: Дайын APK-ны сақтау
        uses: actions/upload-artifact@v4
        with:
          name: Seeker-APK
          path: bin/*.apk
